# config_appengine_v2.yaml
# Run by Python 3.7
runtime: python37
# Machine config  https://cloud.google.com/appengine/docs/standard
instance_class: B2
manual_scaling:
  instances: 1
# Timeout is 60sec
entrypoint: gunicorn -b :$PORT main_v2:app.server --timeout 60 --workers 1
# Instance name
service: app
handlers:
  - url: /.*
    script: auto
    secure: always
